suppressMessages(library(monocle))
suppressMessages(library(Seurat))
#suppressMessages(library(DESeq2))
suppressMessages(library(BiocParallel))
suppressMessages(library(getopt))
suppressMessages(library(gridExtra))
suppressMessages(library(gProfileR))
suppressMessages(library(RColorBrewer))
suppressMessages(library(readxl))
suppressMessages(library(stringr))
suppressMessages(library(scales))
suppressMessages(library(grid))



source("R_src/getSigPerCells.R")
source("R_src/Enrichment.R")
source("R_src/funForSeurat.R")


spec = matrix(c(
  'help',        'h', 0, "logical",   "Help about the program",
  'inputRDS',  'i', 1, "character", "REQUIRED : seurat data analysed object (.RDS generated by prepare_data.R).",
  'inputDCA', 'j', 1, "character", "REQUIRED : dca corrected data matrix (mean.tsv)",
  'outdir',     'o',1, "character", 'Outdir path (default ./)',
  "setActiveIdent", "a", 1, "character", "Set the active ident of the Seurat object (default is NULL opt$SeuratWorkflow is false else \"DCA_snn_\"opt$res )",
  "logfc_threshold", "l", 1, "numeric", "logfc threshold for finding idents markers (1 ident vs all deg 0.25 by default)",
  "rodriguezSig", "k", 1, "character", "path for xls file of Rodriguez result to test enrichment of the markers",
  "identRemoved",    "d", 1, "character", "Optionnal: cluster to remove only work if input is a seurat object",
  "gprofiler", "g", 0, "logical", "if true doing gprofiler on ident markers (default to true)",
  "signaturesFile", "s", 1, "character", "path to folder with signature list store as rds object",
  'SeuratWorkflow', "w", 0, "logical", "If true scale data with correction parameters and perform the classical (one sample no integration) seurat 3 workflow. \nNon expressed genes have to be removed previously. \nThe following parameters will be used: ",
  "num_dim",      'n',1,"numeric", "Number of dimension to use for ordering (eg n first pc of PCA on input data) 10 by default",
  "correction",      "b",1,"character", "Covariable to use as blocking factor (eg one or several columns of pData: betch, cell cycle phases... separated by +)",
  "resolution", "r", 1,"numeric", "resolution for Seurat clustering 0.9 by default",
  "clusterTree", "t", 0, "logical", "if true doing clustree default to false"
), byrow=TRUE, ncol=5);

opt = getopt(spec)


# if help was asked, print a friendly message
# and exit with a non-zero error code

args <- commandArgs()
if ( !is.null(opt$help) | is.null(opt$inputRDS) | is.null(opt$inputDCA)) {
  cat("Add DCA slot in a seurat object and look at markers of the active ident of the seurat object (previously obtained) on dca normalized count with Seurat3 package. \nCan also perform classical Seurat3 workflow (one sample no integration) on the dca corrected data")
  cat(getopt(spec, usage=TRUE))
  q(status=1)
}


#set default arguments values


# if help was asked, print a friendly message
# and exit with a non-zero error code

args <- commandArgs()
if ( !is.null(opt$help) | is.null(opt$inputRDS)) {
  cat("Perform PCA, tSNE, UMAP, Louvain clustering, diff expression between clusters with Seurat3 package with filtered poor quality cells data (gbm_cds monocle object)")
  cat(getopt(spec, usage=TRUE))
  q(status=1)
}

blank <- grid.rect(gp=gpar(col="white"))

#set default arguments values



if (is.null(opt$logfc_threshold)) {
  opt$logfc_threshold = 0.25
} 

print(paste("logfc threshold:", opt$logfc_threshold) )

if (is.null(opt$outdir)) {
  opt$outdir = "./"
}


if (is.null(opt$gprofiler)) {
  opt$gprofiler <- T
} else {
  opt$gprofiler <- F
}

print(opt$gprofiler)






dir.create(opt$outdir,recursive = T,showWarnings = F)

seurat <- readRDS(opt$inputRDS)
dcaMatrix <- read.table(opt$inputDCA,row.names = 1,header = T)
colnames(dcaMatrix) <- gsub(pattern = "\\.",x = colnames(dcaMatrix),replacement = "-")


seurat[["DCA"]] <- CreateAssayObject(counts = dcaMatrix)

DefaultAssay(seurat) <- "DCA"
seurat <- NormalizeData(object = seurat)


#################################################################################################
####################################### Seurat Workflow #########################################
#################################################################################################


if (!is.null(opt$SeuratWorkflow)) {
  corrections <- strsplit(x = opt$correction,split = "\\+")[[1]]
  print("Perform seurat workflow")
  
  seurat <- FindVariableFeatures(object = seurat,selection.method = "vst", nfeatures = 2000, verbose = T)
  seurat <- ScaleData(object = seurat,vars.to.regress = corrections)  
  
  if (is.null(opt$num_dim)) {
    opt$num_dim <- 10
  }
  
  if (is.null(opt$resolution)) {
    opt$resolution <- 0.8
  }
  
  
  seurat <- RunPCA(object = seurat)
  
  
  png(paste(opt$outdir,"/ElbowPlot.png",sep =""))
  ElbowPlot(object = seurat,ndims = 30)
  dev.off()
  
  
  
  seurat <- FindNeighbors(object = seurat,dims = c(1:opt$num_dim),k.param = 20)
  seurat <- FindClusters(object = seurat,resolution = c(0.5,0.6,0.7,0.8,0.9,1,1.2))
  seurat <- RunTSNE(seurat,dims = c(1:opt$num_dim))
  seurat <- RunUMAP(seurat,dims = c(1:opt$num_dim))
  
  colPrefix <- "DCA_snn_res."
  
  umapListRes <- list()
  tsneListRes <- list()
  for (r in c(0.6,0.8,1,1.2)) {
    umapListRes[[as.character(r)]] <- DimPlot(seurat,
                                              reduction = "umap",
                                              label = T,
                                              group.by = paste(colPrefix,r,sep="")) + 
      NoLegend() +
      ggtitle(paste("res",r))
    
    tsneListRes[[as.character(r)]] <- DimPlot(seurat,
                                              reduction = "tsne",
                                              label = T,
                                              group.by = paste(colPrefix,r,sep="")) + 
      NoLegend() +
      ggtitle(paste("res",r))
  }
  
  png(paste(opt$outdir,"/tsne_different_res.png",sep = ""),height = 800,width = 800)
  grid.arrange(tsneListRes[[1]],tsneListRes[[2]],tsneListRes[[3]],tsneListRes[[4]])
  dev.off()
  
  png(paste(opt$outdir,"/umap_different_res.png",sep = ""),height = 800,width = 800)
  grid.arrange(umapListRes[[1]],umapListRes[[2]],umapListRes[[3]],umapListRes[[4]])
  dev.off()
  
  
  
  
  Idents(seurat) <- paste(colPrefix,opt$resolution,sep = "")
  
  seurat@meta.data$numclust <- seurat@meta.data[,paste(colPrefix,opt$resolution,sep = "")]
  
  
  #umap <- DimPlot(seurat,reduction = "umap",label = T,group.by = 'RNA_snn_res.0.8') + NoLegend()
  
  #Check for unwanted source of variation
  pPhases <- DimPlot(seurat,group.by = "phases")
  if (!is.null(seurat@meta.data$predicted)) {
    pPred <- DimPlot(seurat,group.by = "predicted")
  } else {
    pPred <- blank
  }
  pUMI <- FeaturePlot(seurat, "Total_mRNAs")
  #pGenes <- FeaturePlot(seurat,"num_genes_expressed")
  pMito <- FeaturePlot(seurat, "percentMito")
  #pRibo <- DimPlot(seurat,group.by = "percentRibo")
  
  png(paste(opt$outdir,"/umap_factors.png",sep = ""),height = 800,width = 800)
  grid.arrange(pPhases,pPred,pUMI,pMito)
  dev.off()
  
  #Check for unwanted source of variation
  pPhases <- DimPlot(seurat,group.by = "phases",reduction = "tsne")
  if (!is.null(seurat@meta.data$predicted)) {
    pPred <- DimPlot(seurat,group.by = "predicted",reduction = "tsne")
  } else {
    pPred <- blank
  }
  pUMI <- FeaturePlot(seurat, "Total_mRNAs",reduction = "tsne")
  #pGenes <- FeaturePlot(seurat,"num_genes_expressed",reduction = "tsne")
  pMito <- FeaturePlot(seurat, "percentMito",reduction = "tsne")
  #pRibo <- DimPlot(seurat,group.by = "percentRibo",reduction = "tsne")
  
  png(paste(opt$outdir,"/tsne_factors.png",sep = ""),height = 800,width = 800)
  grid.arrange(pPhases,pPred,pUMI,pMito)
  dev.off()
  
  
  #Check for genes
  
  gene_list<- c("Pdzk1ip1","Mllt3",
                "Ctla2a","Cd27","Cd34",
                "Lig1","Hells","Tyms",
                "Notch2","Lst1",
                "Irf7","Stat1",
                "Pf4","Itga2b",
                "Klf1","Gata1",
                "Mpo","Cd48",
                "Fcer1a","Hdc",
                "Il7r","Thy1", # Ccr9 not found
                "Cdc20","Ccnb1","Racgap1",
                "Mzb1","Ly6d", "Trp53inp1",
                "Jun","Fos","Nr4a1")
  
  gene_list <- gene_list[which(is.element(set=rownames(seurat),el = gene_list))] 
  
  dir.create(paste(opt$outdir,"/genes/umap/",sep =""),recursive = T)
  dir.create(paste(opt$outdir,"/genes/tsne/",sep =""),recursive = T)
  for (g in gene_list) {
    png(paste(opt$outdir,"/genes/umap/",g,".png",sep = ""))
    plot(FeaturePlot(seurat,features = g))
    dev.off()
  }
  
  for (g in gene_list) {
    png(paste(opt$outdir,"/genes/tsne/",g,".png",sep = ""))
    plot(FeaturePlot(seurat,features = g),reduction = "tsne")
    dev.off()
  }
  
  
  
} else {
  Idents(seurat) <- opt$setActiveIdent
}

###################################################################################################
########################## Find ident markers on DCA slot #########################################
###################################################################################################


markers <- FindAllMarkers(seurat,only.pos = T,logfc.threshold= opt$logfc_threshold)
markers <- markers[which(markers$p_val_adj < 0.05),]

write.table(x = markers,paste(opt$outdir,"/markers.tsv", sep =""),sep = "\t",quote = F,row.names = F,col.names = T)


dir.create(paste(opt$outdir,"/markers/",sep = ""))

ylab <- "LogNormalized DCA mean"


for (numClust in unique(markers$cluster)) {
  print(head(markers[which(markers$cluster == numClust),],n=9))
  png(paste(opt$outdir,"/markers/Cluster_",numClust,"_topGenesVlnPlot.png",sep =""),width = 1000, height = 1000)
  plot(VlnPlot(object = seurat, features = head(markers[which(markers$cluster == numClust),"gene"],n=9),pt.size = 0.5) + 
         labs(x = "Clusters",y= ylab,colour = "black") +
         theme(axis.text = element_text(size=20),
               plot.title = element_text(size=25)) )
  dev.off()
  
}

#################################################################################################
##########                                Enrichment                                   ##########
#################################################################################################
## Add signatures
dir.create(paste(opt$outdir,"/cellSignatures/",sep = ""))
signatures <- readRDS(opt$signaturesFile)


for (sig in c(1:length(signatures))) {
  sigName <- names(signatures)[sig]
  signature <- signatures[[sig]]
  seurat <- scoreCells3(seurat,signature,outdir= paste(opt$outdir,"/cellSignatures/",sep=""),sigName)
}

## Enrichment

# Modify colnames of markers to use gProfileAnalysis function
firstup <- function(x) {
  substr(x, 1, 1) <- toupper(substr(x, 1, 1))
  x
}

colnames(markers) <- firstup(colnames(markers))


#be careful background
if(opt$gprofiler) {
  gprofiler_result <- gProfileAnalysis(deg_clust = markers,
                                       outdir = paste(opt$outdir,"/gProfileR", sep =""),
                                       background = rownames(seurat),
                                       colors = hue_pal()(length(unique(markers$Cluster))))
  
  saveRDS(gprofiler_result,file=paste(opt$outdir,"/gProfileR/gprofiler_results.rds",sep =""))
}



# Test Rodriguez cluster sig
if(!is.null(opt$rodriguezSig)) {
  
  clusterNames <- c("C1","C2","C3","Mk","Er","Ba","Neu","Mo1","Mo2", "preDC","preB","preT")
  
  RodriguezClustersSig <- lapply(X= c(1:length(clusterNames)),FUN = read_xlsx,path = opt$rodriguezSig)
  
  names(RodriguezClustersSig) <- clusterNames 
  
  getOnlyPos <- function(clustersSig) {
    clusterSig <- clustersSig[which(clustersSig$log.effect > 0),]
    return(clusterSig)
  }
  
  RodriguezClustersSigPos <- lapply(X= RodriguezClustersSig, getOnlyPos)
  
  
  signaturesRodriguez <- lapply(RodriguezClustersSigPos,"[[",1 )
  
  
  firstup <- function(x) {
    substr(x, 1, 1) <- toupper(substr(x, 1, 1))
    x
  }
  
  colnames(markers) <- firstup(colnames(markers))
  
  getClustEnrichForRodriguez <- function(clust,signatures,seurat,markers) {
    clustSig <- lapply(signatures,testHyperSig3,seurat,markers,clust)
    if (!is.null(seurat@meta.data$predicted)) {
      propCellTypesLearned <- table(seurat@meta.data[which(seurat@meta.data$numclust==clust),"predicted"])/length(seurat@meta.data[which(seurat@meta.data$numclust==clust),"predicted"])
    } else{
      propCellTypesLearned <- NULL
    }
    clustInfo <- c(clustSig,propCellTypesLearned)
    return(clustInfo)
  }
  
  clust_list <- lapply(unique(markers$Cluster),getClustEnrichForRodriguez,signature=signaturesRodriguez,seurat =seurat,markers =markers) ##markers arg forgotten in testHyper sig
  
  names(clust_list) <- paste("cluster_",unique(markers$Cluster),sep="")
  
  clust_table <- as.data.frame(matrix(unlist(clust_list), nrow=length(unlist(clust_list[1]))))
  colnames(clust_table) <- names(clust_list)
  rownames(clust_table) <- names(clust_list[[1]])
  
  clust_df <- as.data.frame(t(clust_table))
  
  write.csv(clust_df,file = paste(opt$outdir,"/clustInfoRodriguez.csv",sep =""),quote = F)
  
}


#Clusters table

clust_table <- data.frame()

print("begin cluster table")

getClustInfo <- function(clust,signatures,testHyperSig,seurat,markers) { ## Forgot markers in the arg
  ##TODO Try if it works with markers arg
  
  clustInfo <- list()
  clustInfo$num_cells <- dim(seurat@meta.data[which(seurat@active.ident==clust),])[1]
  clustInfo$percent_cells <- clustInfo$num_cells/dim(seurat@meta.data)[1]
  percentPhases <- table(seurat@meta.data[which(seurat@active.ident==clust),"phases"])/length(seurat@meta.data[which(seurat@active.ident==clust),"phases"]) #In fact this is fraction not percentage
  
  if(!is.null(seurat@meta.data$predicted)) {
    percentPredicted <- table(seurat@meta.data[which(seurat@active.ident==clust),"predicted"])/length(seurat@meta.data[which(seurat@active.ident==clust),"predicted"]) #In fact this is fraction not percentage
    
    for (p in unique(seurat@meta.data$predicted)) {
      print(p)
      if (is.element(p,names(percentPhases))) {
        clustInfo[[p]] <- percentPhases[p] 
      } else {
        clustInfo[[p]] <- 0
      }
    }
    
  }
  
  
  
  for (p in c("G1_G0","S","G2_M")) {
    if (is.element(p,names(percentPhases))) {
      clustInfo[[p]] <- percentPhases[p] 
    } else {
      clustInfo[[p]] <- 0
    }
  }
  
  
  clustInfo$median_genes_expressed <- median(seurat@meta.data[which(seurat@active.ident==clust),"numGenesPerCells"])
  clustInfo$median_nUMI <- median(seurat@meta.data[which(seurat@active.ident==clust),"Total_mRNAs"])
  clustInfo$median_percentMitochGenes <- median(seurat@meta.data[which(seurat@active.ident==clust),"percentMito"])
  
  
  clustSig <- lapply(signatures,testHyperSig3,seurat,markers,clust) ##TODO try if it works with markers arg
  
  clustInfo <- c(clustInfo,clustSig)
  
  
}

allSignatures <- c(signatures,signaturesRodriguez)

clust_list <- lapply(levels(unique(seurat@active.ident)),getClustInfo,allSignatures,testHyperSig,seurat,markers) ##markers arg forgotten in testHyper sig

names(clust_list) <- paste("cluster_",levels(unique(seurat@active.ident)),sep="")

print("clust_list ok")
saveRDS(clust_list,paste(opt$outdir,"/clust_list_save.rds",sep =""))

clust_table <- as.data.frame(matrix(unlist(clust_list), nrow=length(unlist(clust_list[1]))))
colnames(clust_table) <- names(clust_list)
rownames(clust_table) <- names(clust_list[[1]])

print("clust_table ok")

clust_df <- as.data.frame(t(clust_table))

write.table(x = clust_df,file = paste(opt$outdir,"/clusters_table.tsv",sep =""),sep="\t",quote=F,col.names = NA)

saveRDS(seurat,file = paste(opt$outdir,"/seuratDca.rds",sep = ""))

write.csv(x= GetAssayData(seurat,slot = "data"), paste(opt$outdir,"/dca_norm.csv",sep = ""))




