# Script to make analyzis of pseudotime with a gbm_cds ordered 
# command line interface

## -----------------------------------------------------------------------------
## Libraries
## -----------------------------------------------------------------------------


suppressMessages(library(monocle))
suppressMessages(library(getopt))
suppressMessages(library(biomaRt))

source("R_src/Enrichment.R")



spec = matrix(c(
  'help',        'h', 0, "logical",   "Help about the program",
  'inputData',  'i', 1, "character", "REQUIRED: matrix data (.tsv generated by the report) from 10X data ordered by monocle.",
  'outdir',     'o',1, "character", 'Outdir path (default ./)',
  'firstFilter',   'f',1,"numeric", 'Keep only the genes with at least N = f(X) 2 mean imputed counts across all samples (X=2 by default) \n(e.g. the total number the gene would have, if it was expressed with a value of X in 1% of the cells). \nAdjust X value according to the dataset (it will depend on the dataset units, e.g. UMI, TPMs???).',
  'secondFilter',  's',1, "numeric", 'Keep the genes that are detected in at least X% of the cells (X=1% by default)'
), byrow=TRUE, ncol=5);

opt = getopt(spec)



# if help was asked, print a friendly message
# and exit with a non-zero error code

args <- commandArgs()
if ( !is.null(opt$help) | is.null(opt$inputData)) {
  cat("Gene filtering of a gbm cds ordered. For scenic use, two filters")
  cat(getopt(spec, usage=TRUE))
  q(status=1)
}

#set default arguments values

if (is.null(opt$outdir)) {
  opt$outdir = "./"
}
if (is.null(opt$firstFilter)) {
  opt$firstFilter = 2
}
if (is.null(opt$secondFilter)) {
  opt$secondFilter = 0.01
}

data <- read.table(opt$inputData,sep = "\t",header = T,row.names = 1)

genes <- list()
genes$names <- rownames(data)


nCellsPerGene <- apply(data, 1, function(x) sum(x>0))
nCountsPerGene <- apply(data, 1, sum)
summary(nCellsPerGene)
sum(data>0) / sum(data==0)

#first filter
minReads <- opt$firstFilter*.01*ncol(data)
genesLeftMinReads <- names(nCountsPerGene)[which(nCountsPerGene > minReads)]
length(genesLeftMinReads)

#second filter
minSamples <- ncol(data)*opt$secondFilter
nCellsPerGene2 <- nCellsPerGene[genesLeftMinReads]
genesLeftMinCells <- names(nCellsPerGene2)[which(nCellsPerGene2 > minSamples)]
length(genesLeftMinCells)



t_data <- t(data)

print(head(genesLeftMinCells))

write.table(t_data[,c(genesLeftMinCells)],file = paste(opt$outdir,"/expressionRawCountFilteredForScenic.tsv",sep=""),sep = '\t',quote = F)






