suppressMessages(library(monocle))
suppressMessages(library(Seurat))
suppressMessages(library(scales))
#suppressMessages(library(BiocParallel))
suppressMessages(library(getopt))
#suppressMessages(library(gridExtra))
#suppressMessages(library(gProfileR))
suppressMessages(library(RColorBrewer))
#suppressMessages(library(readxl))
#suppressMessages(library(stringr))


#source("R_src/getSigPerCells.R")
#source("R_src/Enrichment.R")
#source("R_src/funForSeurat.R")
colorPhases <- c(brewer.pal(9,"RdPu"))[c(3,6,9)]
colorCellType <- c(brewer.pal(4,"Set2"))[c(1,3,4,2)]
colorAge <-  c("#FF8000","#664CFF")
colorTrajStateFinal <- c("#999999", "#E69F00", "#56B4E9", "#009E73","#F0E442")
colorTrajStateFinal <- colorTrajStateFinal[c(1,5,4,2,3)]
colorClusters <- c("#999999","#004949","#009292","#ff6db6","#ffb6db",
                   "#490092","#006ddb","#b66dff","#6db6ff","#b6dbff",
                   "#920000","#924900","#db6d00","#24ff24","#ffff6d")
colorCellType <- c(brewer.pal(4,"Set2"))[c(1,3,4,2)]
colorCellTypePerturb <- hue_pal()(4)[c(2,3,4,1)]

spec = matrix(c(
  'help',        'h', 0, "logical",   "Help about the program",
  'inputRDS',  'i', 1, "character", "REQUIRED : 10X data prepared as seurat object (.RDS generated by report previous study).",
  'outdir',     'o',1, "character", 'Outdir path (default ./)',
  "prefix", "p", 1, "character", "Prefix for the output file",
  "monocleRDS", "m", 1,"character", "monocle object to compare trajectory states",
  "removeCluster", "r", 1, "character", "remove cell for the given cluster (need allData)"
), byrow=TRUE, ncol=5)

opt = getopt(spec)

# if help was asked, print a friendly message
# and exit with a non-zero error code

args <- commandArgs()
if ( !is.null(opt$help) | is.null(opt$inputRDS)) {
  cat("Prepare data for trajectory inference with stream")
  cat(getopt(spec, usage=TRUE))
  q(status=1)
}

if (is.null(opt$outdir)) {
  opt$outdir = "./"
}



## For testing
#opt <- list()
#opt$inputRDS <- "../herault_et_al/scHSC_herault/report/seurat_report.rds"
#opt$removeCluster <- "pL2"
#opt$prefix <- "all"
#opt$monocleRDS <- "../herault_et_al/scHSC_herault/report/monocle_report.rds"

print(opt)

dir.create(opt$outdir)

prefix <- opt$prefix

print(prefix)

seurat <- readRDS(opt$inputRDS)
DefaultAssay(seurat) <- 'integrated'
Idents(seurat) <- "numclust"

# remove cluster if specified
if (!is.null(opt$removeCluster)) {
  seurat <- subset(seurat,ident=opt$removeCluster,invert = T)
}


data <- GetAssayData(object = seurat, slot = "scale.data")
data <- data[,rownames(seurat@meta.data)]



write.table(data,paste(opt$outdir,"/",prefix,"_scaleDataForStream.tsv",sep = ""),quote = FALSE, sep = "\t",col.names = T)




#Write anno data predicted cell types
cellColors <- cbind(c("LTHSC","STHSC","MPP2","MPP3"),colorCellType)
write.table(seurat$predicted,paste(opt$outdir,"/",prefix,"_predictedCellTypes.tsv",sep =""),quote = FALSE,sep = "\t",col.names = FALSE)
write.table(cellColors,paste(opt$outdir,"/",prefix,"_colorCellTypes.tsv",sep =""),quote = FALSE,sep = "\t",col.names = FALSE,row.names = F)

## add final clust info
names(colorClusters) <- levels(seurat$numclust)
colorClusters <- cbind(v=names(colorClusters)[-which(names(colorClusters) == opt$removeCluster)],
                       colorClusters[-which(names(colorClusters) == opt$removeCluster)])
write.table(colorClusters,paste(opt$outdir,"/",prefix,"_colorClusters.tsv",sep =""),quote = FALSE,sep = "\t",col.names = FALSE,row.names = F)
write.table(seurat$numclust,paste(opt$outdir,"/",prefix,"_seuratClusters.tsv",sep = ""),quote = FALSE,sep = "\t",col.names = FALSE,row.names = F)


#Write phases anno data
cellPhaseColor <- cbind(v = c("G1/G0","S","G2/M"),colorPhases)
write.table(seurat$phases,paste(opt$outdir,"/",prefix,"_phases.tsv",sep = ""),quote = FALSE,sep = "\t",col.names = FALSE,row.names = F)
write.table(cellPhaseColor,paste(opt$outdir,"/",prefix,"_colorPhases.tsv",sep =""),quote = FALSE,sep = "\t",col.names = FALSE,row.names = F)

#Write age anno data
cellAgeColor <- cbind(v = c("Young","Aged"),colorAge)
write.table(seurat$AGE,paste(opt$outdir,"/",prefix,"_ages.tsv",sep = ""),quote = FALSE,sep = "\t",col.names = FALSE,row.names = F)
write.table(cellAgeColor,paste(opt$outdir,"/",prefix,"_colorAges.tsv",sep =""),quote = FALSE,sep = "\t",col.names = FALSE,row.names = F)


#Write monocle traj
monocle <- readRDS(opt$monocleRDS)
seurat$State <- pData(monocle)[colnames(seurat),"State"]
write.table(seurat$State,paste(opt$outdir,"/",prefix,"_monocleStates.tsv",sep = ""),quote = FALSE,sep = "\t",col.names = FALSE,row.names = F)
cellStateColors <- cbind(c(1:5),colorTrajStateFinal)
write.table(cellStateColors,paste(opt$outdir,"/",prefix,"_colorMonocleStates.tsv",sep =""),quote = FALSE,sep = "\t",col.names = FALSE,row.names = F)


